<?php
echo "GEOIP_CONTINENT_CODE: ".$_SERVER["GEOIP_CONTINENT_CODE"]."<br>";
echo "GEOIP_COUNTRY_CODE: ".$_SERVER["GEOIP_COUNTRY_CODE"]."<br>";
echo "HTTP_CF_IPCOUNTRY: ".$_SERVER["HTTP_CF_IPCOUNTRY"]."<br>";
?>